#! /bin/sh -e

# Copyright (C) 2018 Tomoyuki Fujimori <moyu@dromozoa.com>
#
# This file is part of dromozoa-dotfiles.
#
# dromozoa-dotfiles is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# dromozoa-dotfiles is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with dromozoa-dotfiles.  If not, see <http://www.gnu.org/licenses/>.

if (unset CDPATH) >/dev/null 2>&1
then
  unset CDPATH
fi

fn_dirname() {
  expr "x$1" : 'x\(.*[^/]\)//*[^/][^/]*/*$' \
    '|' "x$1" : 'x\(//\)[^/]' \
    '|' "x$1" : 'x\(//\)$' \
    '|' "x$1" : 'x\(/\)' \
    '|' .
}

here=`fn_dirname "$0"`
here=`(cd "$here" && pwd)`
backup=$here/backup-`date "+%Y-%m-%d-%H-%M-%S"`

cd
home=`pwd`

for i in .bashrc .editrc .inputrc .screenrc .vimrc .zshrc
do
  if test -h "$i"
  then
    echo "unlink $home/$i"
    rm -f "$i"
  elif test -f "$i"
  then
    echo "move $home/$i -> $backup"
    mkdir -p "$backup"
    mv -f "$i" "$backup"
  fi
  echo "link $home/$i -> $here/$i"
  ln -s "$here/$i" "$i"
done
